### ISSUE TITLE
getSelectedItem on material spinner

### ISSUE THREAD

**Issue by mehdi-salehi** [ganfra/MaterialSpinner#20] opened 2015-06-30 04:42 UTC
getSelectedItem on material spinner returns id+1 from cursor adapter.
why?

Cursor cc=(Cursor) w41_spinner.getSelectedItem(); =>12  instead 11

**Comment by ganfra** [comment] 2015-07-01 08:03
Could you please provide your sample code ? Because I can't reproduce this issue

**Comment by Wanjau** [comment] 2015-08-07 09:20
Am late but this is what worked for me

String[] ITEMS = {"Mobile Phones", "Electronics", "Fashion and Beauty", "Vehicles", "Real Estate", "Jobs and Services"
        ,"Hotel and Accomodation","Financial and Insurance","Tours and Travel","Houselhold Appliances","Others"};

        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_item, ITEMS);
         adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        categories = (MaterialSpinner) findViewById(R.id.categories);
        subcategories = (MaterialSpinner) findViewById(R.id.subcategories);
        shit = (TextView)findViewById(R.id.shit);

        categories.setAdapter(adapter);
        categories.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                selected=String.valueOf(categories.getSelectedItem());
                shit.setText(selected);
                if(selected.contentEquals("Mobile Phones")){
                    String[] phones={"Android","Windows","Ios"};
                    ArrayAdapter<String> phoneadapter= new ArrayAdapter<String>(getApplicationContext(),
                            android.R.layout.simple_expandable_list_item_1,phones);
                    subcategories.setAdapter(phoneadapter);

                }

            }

            @Override
            public void onNothingSelected(AdapterView<?> parent) {

            }
        });

**Comment by Gautham** [comment] 2015-09-25 08:14
Hi. Very late to post this but I came into a similar issue myself.
The problem lies in that although the listener is passed the correct index as per the adapter we pass, the AdapterView now has an extra entry for the Hint. Therefore, calling parent.getItemAtSelection() will return an incorrect item unless you use (position + 1) if you use hint.

I'm not sure how you'd ideally fix this but I guess you could override the method that calls onItemSelected() and pass it position + 1 if hint is enabled. Otherwise, the user needs to explicitly give (position + 1) index himself.

**Comment by ganfra** [comment] 2015-10-12 13:01
Sorry for the late ! Yes it's an error from me, a new release will be out soon to correct some stuff !

**Comment by mdumrauf** [comment] 2017-09-16 01:55
This was fixed in v1.1.1

**Closed by mdumrauf** 2017-09-16 01:55 UTC
