### ISSUE TITLE
android:entries is not working.

### ISSUE THREAD

**Issue by diofeher** [ganfra/MaterialSpinner#14] opened 2015-05-22 01:54 UTC
android:entries is not working. It shows only the name at "hint" option.

**Comment by vj-1023** [comment] 2015-06-23 03:44
same problem.
Only hint displayed

**Comment by ganfra** [comment] 2015-10-12 13:50
Sorry for the very late answer ... I can't reproduce your error, could you provide me your exact xml ?

**Comment by asinel** [comment] 2017-08-01 12:22
When I use "entries", it shows hint 2 times

**Comment by mdumrauf** [comment] 2017-09-10 06:01
I am getting the same error as @asinel

**Comment by mdumrauf** [comment] 2017-09-16 01:52
Fixed in #49

**Closed** 2017-09-16 07:24 UTC
