### ISSUE TITLE
 D/OpenGLRenderer: endAllActiveAnimators on (DropDownListView) with handle.

### ISSUE THREAD

**Issue by omtodkar** [ganfra/MaterialSpinner#89] opened 2017-04-24 13:03 UTC
On selecting second item in dropdown (just next value after `ms_hint`), it doesn't call OnItemSelected event. I am getting below log in logcat.

`D/OpenGLRenderer: endAllActiveAnimators on 0x8516b680 (DropDownListView) with handle 0x8517e360`

This is xml configured MaterialSpinner:

    <fr.ganfra.materialspinner.MaterialSpinner
                android:id="@+id/distributor"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginBottom="10dp"
                app:ms_alignLabels="true"
                app:ms_arrowColor="@color/colorPrimaryDark"
                app:ms_arrowSize="10dp"
                app:ms_baseColor="@color/colorPrimary"
                app:ms_enableErrorLabel="true"
                app:ms_enableFloatingLabel="true"
                app:ms_errorColor="@color/accent_light"
                app:ms_floatingLabelColor="@color/primary_light"
                app:ms_floatingLabelText="@string/registration_select_distributor"
                app:ms_highlightColor="@color/primary_text_color"
                app:ms_hint="@string/registration_distributor"
                app:ms_hintColor="@color/colorPrimary"
                app:ms_multiline="false" />

**Comment by i39anisimov** [comment] 2017-06-27 10:43
Any solutions? Same issue

**Comment by Subratsss** [comment] 2017-06-28 06:53
I have same issues

**Comment by i39anisimov** [comment] 2017-06-28 19:08
@Subratsss i've solved my issue.
I forgot that notifyDataSetChanged should be called in **main thread**. Check in which thread you call it.

**Comment by mdumrauf** [comment] 2017-09-16 17:30
I can't reproduce this issue. As @i39anisimov said, it seems not to be a bug in the library. Closing for now, feel free to reopen if necessary.

**Closed by mdumrauf** 2017-09-16 17:30 UTC

**Comment by barryjohncoronel** [comment] 2019-09-19 16:06
> @Subratsss i've solved my issue.
> I forgot that notifyDataSetChanged should be called in **main thread**. Check in which thread you call it.

How did you fixed the issue?

**Comment by frared358** [comment] 2020-03-05 07:01
I am also facing this issues.. How did you fixed the issue..?
please help..

**Comment by IamJeenu** [comment] 2021-05-29 20:00
distributor.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                final String item= distributor.getText().toString().trim();
                Log.i(TAG, "MyClass.getView() — get item number " + ite
            }
        });

Use this : its working fine : if u facing same issue then u msg me  on this Instagram id  : @iamjeevan01 i am available
